### ISSUE TITLE
Linux, ver. 1.2.32 - Errors on startup

### ISSUE THREAD

**Issue by giacecco** [intechstudio/grid-editor#236]
See below. The application starts but is unresponsive. The terminal shows the error messages below. I am running it on the latest Ubuntu LTS (5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC).

From the look of it, the error is trivial: you are trying to use a IP port that is already in use by some other application.

This is the first time I use Linux for the Grid Editor. I have to, because the IT people at work have blocked the use of USB storage on my Mac, so I would not be able to update the Grid elements' firmware. I own 8 of them, I'm a big client of yours :-) Thanks.

```
giacecco@giacecco-ThinkPad-X270-W10DG:/opt$ ./grid-editor-setup-1.2.32-release.AppImage &
[2] 31121
giacecco@giacecco-ThinkPad-X270-W10DG:/opt$ 08:13:52.667 › check for update and notify...
08:13:52.674 › Checking for update
08:13:52.676 › App starting...
deeplink receive --allow-file-access-from-files
deeplink receive --allow-file-access-from-files
08:13:52.695 › Checking for update (already in progress)
Deeplink {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  checkConfig: [Function (anonymous)],
  setAppProtocol: [Function (anonymous)],
  secondInstanceEvent: [Function (anonymous)],
  darwinOpenEvent: [Function (anonymous)],
  restoreInfoPlist: [Function (anonymous)],
  getProtocol: [Function (anonymous)],
  getLogfile: [Function (anonymous)],
  config: {
    protocol: 'grid-editor',
    debugLogging: false,
    isDev: false,
    electronPath: '/node_modules/electron/dist/Electron.app'
  },
  app: App {
    quit: [Function: quit],
    exit: [Function: exit],
    focus: [Function: focus],
    getVersion: [Function: getVersion],
    setVersion: [Function: setVersion],
    getName: [Function: getName],
    setName: [Function: setName],
    isReady: [Function: isReady],
    whenReady: [Function: whenReady],
    addRecentDocument: [Function: addRecentDocument],
    clearRecentDocuments: [Function: clearRecentDocuments],
    isDefaultProtocolClient: [Function: isDefaultProtocolClient],
    setAsDefaultProtocolClient: [Function: setAsDefaultProtocolClient],
    removeAsDefaultProtocolClient: [Function: removeAsDefaultProtocolClient],
    getApplicationNameForProtocol: [Function: getApplicationNameForProtocol],
    setBadgeCount: [Function: setBadgeCount],
    getBadgeCount: [Function: getBadgeCount],
    getLoginItemSettings: [Function: getLoginItemSettings],
    setLoginItemSettings: [Function: setLoginItemSettings],
    isEmojiPanelSupported: [Function: isEmojiPanelSupported],
    setAboutPanelOptions: [Function: setAboutPanelOptions],
    showAboutPanel: [Function: showAboutPanel],
    isUnityRunning: [Function: isUnityRunning],
    isPackaged: [Getter],
    setAppPath: [Function: setAppPath],
    getAppPath: [Function: getAppPath],
    setPath: [Function: setPath],
    getPath: [Function: getPath],
    setAppLogsPath: [Function: setAppLogsPath],
    setDesktopName: [Function: setDesktopName],
    getLocale: [Function: getLocale],
    getLocaleCountryCode: [Function: getLocaleCountryCode],
    importCertificate: [Function: importCertificate],
    hasSingleInstanceLock: [Function: hasSingleInstanceLock],
    requestSingleInstanceLock: [Function: requestSingleInstanceLock],
    releaseSingleInstanceLock: [Function: releaseSingleInstanceLock],
    relaunch: [Function: relaunch],
    isAccessibilitySupportEnabled: [Function: isAccessibilitySupportEnabled],
    setAccessibilitySupportEnabled: [Function: setAccessibilitySupportEnabled],
    disableHardwareAcceleration: [Function: disableHardwareAcceleration],
    disableDomainBlockingFor3DAPIs: [Function: disableDomainBlockingFor3DAPIs],
    getFileIcon: [Function: getFileIcon],
    getAppMetrics: [Function (anonymous)],
    getGPUFeatureStatus: [Function: getGPUFeatureStatus],
    getGPUInfo: [Function: getGPUInfo],
    userAgentFallback: [Getter/Setter],
    configureHostResolver: [Function: configureHostResolver],
    enableSandbox: [Function: enableSandbox],
    commandLine: {
      hasSwitch: [Function: hasSwitch],
      getSwitchValue: [Function: getSwitchValue],
      appendSwitch: [Function: appendSwitch],
      appendArgument: [Function: appendArgument],
      removeSwitch: [Function: removeSwitch]
    },
    setAppUserModelId: [Function (anonymous)],
    _events: [Object: null prototype] {
      'certificate-error': [Function (anonymous)],
      'select-client-certificate': [Function (anonymous)],
      quit: [Function (anonymous)],
      'window-all-closed': [Function (anonymous)],
      'will-finish-launching': [Function],
      'web-contents-created': [Function (anonymous)]
    },
    _eventsCount: 6,
    allowRendererProcessReuse: false
  },
  mainWindow: undefined,
  [Symbol(kCapture)]: false
}
The server encountered an error! Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at new WebSocketServer (/tmp/.mount_grid-eNjZY57/resources/app.asar/node_modules/ws/lib/websocket-server.js:90:20)
    at startWebsocketServer (/tmp/.mount_grid-eNjZY57/resources/app.asar/dist/main/index.js:260:9)
    at Object.<anonymous> (/tmp/.mount_grid-eNjZY57/resources/app.asar/dist/main/index.js:258:1)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 1337
}
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[31156:0429/081353.177369:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by SukuWc** [comment]
Plugin port is opened on application startup, ws://localhost:1337! Let's make it fail gracefully if port is already used! Scheduled for the next iteration!

**Comment by elsoazemelet** [comment]
Hey!

We've thoroughly investigated this issue in a Linux enviroment with old and new builds, as well as with a debug build where we have isolated the issue.
Port 1337 is used for websocket communication, which feature is currently in developement, and the regarding error message that you have attached is a normal error message when the opening of port 1337 fails.
However, during the investigation we have not found any unresponsivity, or crashes, the modules worked fine.
Please consider that, that you also attached the following error, which to us seem like a driver issue:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

There is a possibility that chromium (on which Grid Editor is based on) does not work that well in a virtualized enviroment, or that it can sometimes break under Ubuntu. 
Since many other people reported the same error when launching chrome or chromium based applications from terminal, we'd suggest to check these threads and let us know if the issue has resolved.
